import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import NavBar from "@/components/navbar";
import Footer from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Milestones",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

        <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="h-screen flex flex-col w-screen items-center overflow-y-clip ">
            <NavBar />
            <div className="h-full w-[55%]">
              {children}
            </div>
            <Footer />
          </div>
          
              



        </body>
      </html>

  );
}
